name: WealthFlow
options:
  bundleIdPrefix: com.example # You can customize this
targets:
  WealthFlow:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Models
      - path: Views
      - path: Services
      - path: ViewModels
      - path: WealthFlowApp.swift
